=== ada-u/bookingkit-API-v3/schemas/vendor.json
{
  "required": true,
  "$schema": "http://json-schema.org/draft-03/schema",
  "type": "object",
  "title": "Vendor",
  "properties": {
    "id": {
      "required": true,
      "type": "string",
      "description": "unique identifier"
    },
    "name": {
      "required": true,
      "type": "string",
      "description": "vendor name, usually a company name"
    },
    "url": {
      "required": false,
      "type": "string",
      "description": "vendor homepage"
    },
    "service_email": {
      "required": false,
      "type": "string",
      "format": "email",
      "description": "contact email for customer service"
    },
    "service_phone": {
      "required": false,
      "type": "string",
      "description": "contact phone for customer service"
    },
    "image": {
      "required": false,
      "type": "string",
      "description": "URL of vendor logo"
    },
    "terms":{
      "required": false,
      "type": "string",
      "description": "vendor business terms"
    },
    "bill_country":{
      "required": true,
      "type": "string",
      "description": "ISO 3166-1 alpha-2 country code"
    },
    "country_of_residence":{
      "required": true,
      "type": "string",
      "description": "ISO 3166-1 alpha-2 country code"
    }
  }
}

=== ada-u/bookingkit-API-v3/examples/vendors.json
[
  {
    "id":"6e65da2bea23fa4340d5f78ee1fda1ae",
    "name":"erlebnis-buchen.com",
    "url":"erlebnis-buchen.com",
    "service_email":"mail@bookingkit.de",
    "service_phone":"030 6095 503-0",
    "image":"https:\/\/app.bookingkit.de\/images\/vendors\/d180c9c1568ff03b45943477bd9656a6\/icon\/logoUeoeoeL1_1ss_.tr.jpg"
  },
  {
    "id":"3858f62230ac3c915f300c664312c63f",
    "name":"reisen-buchen.com",
    "url":"http://www.reisen-buchen.com",
    "service_email":"mail@reisen-buchen.com",
    "service_phone":"030 1234 1230",
    "image":"https:\/\/app.bookingkit.de\/images\/vendors\/3858f62230ac3c915f300c664312c63f\/icon\/logo.jpg"
  }
]

=== ada-u/bookingkit-API-v3/examples/vendor.json
{
  "id":"6e65da2bea23fa4340d5f78ee1fda1ae",
  "name":"erlebnis-buchen.com",
  "url":"erlebnis-buchen.com",
  "service_email":"mail@bookingkit.de",
  "service_phone":"030 6095 503-0",
  "image":"https:\/\/app.bookingkit.de\/images\/vendors\/d180c9c1568ff03b45943477bd9656a6\/icon\/logoUeoeoeL1_1ss_.tr.jpg"
}
